#!/bin/bash
echo "Type the JMP ESP address"
read ESP
for a in $(echo $ESP | cut -c 7,8); do
echo "'\x$a\'" | cut -c 2,3,4,5,6
done
for b in $(echo $ESP | cut -c 5,6); do
echo "'\x$b'" | cut -c 2,3,4,5
done
for c in $(echo $ESP | cut -c 3,4); do
echo "'\x$c'" | cut -c 2,3,4,5
done
for d in $(echo $ESP | cut -c 1,2); do
echo "'\x$d'" | cut -c 2,3,4,5  
done
echo ""
echo "The result is"
echo "'\x$a\x$b\x$c\x$d'" | cut -c 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17


