#!/bin/bash
echo		---------- 
echo "Usage: mymaphttp targethostip targetport(Ex:80)"
echo		----------
nmap -p $2 --script=http-enum,http-webdav-scan,http-iis-webdav-vuln,http-malware-host,http-shellshock,http-sql-injection,http-vuln-cve2006-3392,http-vuln-cve2009-3960,http-vuln-cve2010-0738,http-vuln-cve2010-2861,http-vuln-cve2011-3192,http-vuln-cve2011-3368,http-vuln-cve2012-1823,http-vuln-cve2013-0156,http-vuln-cve2013-6786,http-vuln-cve2013-7091,http-vuln-cve2014-2126,http-vuln-cve2014-2127,http-vuln-cve2014-2128,http-vuln-cve2014-2129,http-vuln-cve2014-3704,http-vuln-cve2014-8877,http-vuln-cve2015-1427,http-vuln-cve2015-1635,http-vuln-cve2017-1001000,http-vuln-cve2017-5638,http-vuln-cve2017-5689,http-vuln-cve2017-8917,http-vuln-misfortune-cookie,http-vuln-wnr1000-creds,http-wordpress-enum,http-wordpress-users,ssl-heartbleed --vv $1 -oN /root/results/http-result-$1.txt && cat /root/results/http-result-$1.txt
